version: '3.8'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_pass
      POSTGRES_DB: job_scraper
    ports:
      - "5432:5432"
    networks:
      - scraper_network

  scraperwebapp:
    build:
      context: ./scraperwebapp
    volumes:
      - ./scraperwebapp:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./scraperwebapp/.env
    networks:
      - scraper_network

  # notebook:
  #   build: 
  #     context: ./notebooks
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./notebooks/.env
  #   networks:
  #     - scraper_network
  #   command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  
networks:
  scraper_network:
    driver: bridge

