version: '3.8'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_pass
      POSTGRES_DB: job_scraper
    ports:
      - "5432:5432"
    networks:
      - scraper_network

  scraperwebapp:
    build:
      context: ./scraperwebapp
    volumes:
      - ./scraperwebapp:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./scraperwebapp/.env
    networks:
      - scraper_network


  
  celery:
    build:
      context: ./scraperwebapp
    command: celery -A scraperwebapp.celery worker -l info
    volumes:
      - ./scraperwebapp:/app
    depends_on:
      - redis
      - postgres
    networks:
      - scraper_network
    env_file:
      - ./scraperwebapp/.env



  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - scraper_network


  
networks:
  scraper_network:
    driver: bridge

