# Generated by Django 5.1 on 2024-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_keyword_job_listings_alter_keyword_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='scheduled_on',
            field=models.DateTimeField(),
        ),
    ]
