# Generated by Django 5.1 on 2024-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_keyword_scheduled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='scheduled_on',
            field=models.TimeField(),
        ),
    ]
